/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 31/10/2025 12:50:18
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            25000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_SYSCLKFreq_VALUE                     16000000
#define MX_HCLKFreq_Value                       16000000
#define MX_FCLKCortexFreq_Value                 16000000
#define MX_CortexFreq_Value                     16000000
#define MX_AHBFreq_Value                        16000000
#define MX_APB1Freq_Value                       16000000
#define MX_APB2Freq_Value                       16000000
#define MX_APB1TimFreq_Value                    16000000
#define MX_APB2TimFreq_Value                    16000000
#define MX_ADC12Freq_Value                      16000000
#define MX_LPUART1Freq_Value                    16000000
#define MX_I2C1Freq_Value                       16000000
#define MX_I2SFreq_Value                        16000000
#define MX_USART1Freq_Value                     16000000
#define MX_USART2Freq_Value                     16000000
#define MX_USART3Freq_Value                     16000000
#define MX_FDCANFreq_Value                      16000000
#define MX_LPTIM1Freq_Value                     16000000
#define MX_SAI1Freq_Value                       16000000
#define MX_PWRFreq_Value                        16000000
#define MX_RTCFreq_Value                        32000
#define MX_USBFreq_Value                        64000000
#define MX_WatchDogFreq_Value                   32000
#define MX_CECFreq_Value                        4000000
#define MX_MCO1PinFreq_Value                    16000000

/*-------------------------------- ADC1       --------------------------------*/

#define MX_ADC1                                 1

/* GPIO Configuration */

/* Pin PA1 */
#define MX_ADC1_IN2_Pin                         PA1
#define MX_ADC1_IN2_GPIOx                       GPIOA
#define MX_ADC1_IN2_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADC1_IN2_GPIO_Pin                    GPIO_PIN_1
#define MX_ADC1_IN2_GPIO_Mode                   GPIO_MODE_ANALOG

/* Pin PA0 */
#define MX_ADC1_IN1_Pin                         PA0
#define MX_ADC1_IN1_GPIOx                       GPIOA
#define MX_ADC1_IN1_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADC1_IN1_GPIO_Pin                    GPIO_PIN_0
#define MX_ADC1_IN1_GPIO_Mode                   GPIO_MODE_ANALOG

/*-------------------------------- ADC2       --------------------------------*/

#define MX_ADC2                                 1

/* GPIO Configuration */

/* Pin PA4 */
#define MX_ADC2_IN17_Pin                        PA4
#define MX_ADC2_IN17_GPIOx                      GPIOA
#define MX_ADC2_IN17_GPIO_PuPd                  GPIO_NOPULL
#define MX_ADC2_IN17_GPIO_Pin                   GPIO_PIN_4
#define MX_ADC2_IN17_GPIO_Mode                  GPIO_MODE_ANALOG

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/* Pin PA13 */
#define MX_SYS_JTMS_SWDIO_Pin                   PA13

/* Pin PA14 */
#define MX_SYS_JTCK_SWCLK_Pin                   PA14

/*-------------------------------- TIM1       --------------------------------*/

#define MX_TIM1                                 1

/* GPIO Configuration */

/* Pin PA8 */
#define MX_S_TIM1_CH1_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM1_CH1_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM1_CH1_Pin                       PA8
#define MX_S_TIM1_CH1_GPIOx                     GPIOA
#define MX_S_TIM1_CH1_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM1_CH1_GPIO_Pin                  GPIO_PIN_8
#define MX_S_TIM1_CH1_GPIO_AF                   GPIO_AF6_TIM1

/* Pin PA9 */
#define MX_S_TIM1_CH2_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM1_CH2_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM1_CH2_Pin                       PA9
#define MX_S_TIM1_CH2_GPIOx                     GPIOA
#define MX_S_TIM1_CH2_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM1_CH2_GPIO_Pin                  GPIO_PIN_9
#define MX_S_TIM1_CH2_GPIO_AF                   GPIO_AF6_TIM1

/* Pin PB0 */
#define MX_TIM1_CH2N_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_TIM1_CH2N_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_TIM1_CH2N_Pin                        PB0
#define MX_TIM1_CH2N_GPIOx                      GPIOB
#define MX_TIM1_CH2N_GPIO_PuPd                  GPIO_NOPULL
#define MX_TIM1_CH2N_GPIO_Pin                   GPIO_PIN_0
#define MX_TIM1_CH2N_GPIO_AF                    GPIO_AF6_TIM1

/* Pin PA7 */
#define MX_TIM1_CH1N_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_TIM1_CH1N_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_TIM1_CH1N_Pin                        PA7
#define MX_TIM1_CH1N_GPIOx                      GPIOA
#define MX_TIM1_CH1N_GPIO_PuPd                  GPIO_NOPULL
#define MX_TIM1_CH1N_GPIO_Pin                   GPIO_PIN_7
#define MX_TIM1_CH1N_GPIO_AF                    GPIO_AF6_TIM1

/* NVIC Configuration */

/* NVIC TIM1_BRK_TIM15_IRQn */
#define MX_TIM1_BRK_TIM15_IRQn_interruptPremptionPriority 0
#define MX_TIM1_BRK_TIM15_IRQn_PriorityGroup    NVIC_PRIORITYGROUP_4
#define MX_TIM1_BRK_TIM15_IRQn_Subriority       0

/* NVIC TIM1_UP_TIM16_IRQn */
#define MX_TIM1_UP_TIM16_IRQn_interruptPremptionPriority 0
#define MX_TIM1_UP_TIM16_IRQn_PriorityGroup     NVIC_PRIORITYGROUP_4
#define MX_TIM1_UP_TIM16_IRQn_Subriority        0

/*-------------------------------- TIM2       --------------------------------*/

#define MX_TIM2                                 1

/* GPIO Configuration */

/* NVIC Configuration */

/* NVIC TIM2_IRQn */
#define MX_TIM2_IRQn_interruptPremptionPriority 0
#define MX_TIM2_IRQn_PriorityGroup              NVIC_PRIORITYGROUP_4
#define MX_TIM2_IRQn_Subriority                 0

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

#endif  /* __MX_DEVICE_H */

